#
#   Copyright (c) 2017 NTT corp. - All Rights Reserved
#
#   This file is part of opcount which is released under Software License
#   Agreement for Evaluation. See file LICENSE.pdf for full license details.
#

ADDITIONAL_CFLAGS=
CTAGS=exctags
YACC=bison -y
LEX=lex
CC=cc
CXX=c++
LD=c++

.include "Makefile"
